### ISSUE TITLE
Crash on Invalid Image File Import

### ISSUE THREAD

**Issue by fengshuo2004** [AlexJason/Zilch-Editor#2]
Program crashes (exits) on invalid image file import through the "import costume from file" window.

- To reproduce:
Although the "import costume" window disallows files other than those of extension `.png`, `.jpg` and `.jpeg`, the program will still import files that are not valid image files. When that happens, click the ClipCC icon that just appeared (Is this a placeholder image?) and the program exits.

I uploaded a file named `new.jpg`, it is 256 bytes long, all of those bytes are filled with `0xFF` to help with diagnosis.

- Log file of that launch:
[log-20190404_202554.log](https://github.com/AlexJason/zilch-editor/files/3043498/log-20190404_202554.log)

- Dump file of that launch (please remove ".log" from its filename):
[20190404-202623.378.dmp.log](https://github.com/AlexJason/zilch-editor/files/3043506/20190404-202623.378.dmp.log)

**Comment by alexcui03** [comment]
# Issue#2
Reason: Subscript out of range. (class: ScratchStage)
## Result
 - BugID: bug#31, bug#32
 - Supporter: Sinan Gentoo

**These bug has been fixed in 0.2.3.638(0.2.3 Release)/0.3.0.665(0.3.0 Alpha 3)**
